#!/bin/sh

. packages/NZBGet/meta
cd mkpkg

echo "building $PKG_NAME..."
echo "getting sources..."
  if [ ! -d build.$PKG_NAME-$PKG_VERSION ]; then
    wget $PKG_URL
    if [ "$?" = "1" ]; then
      echo "error downloading source: $1";exit 1
    fi
    mkdir $PKG_NAME-$PKG_VERSION
    chmod +x $PKG_NAME-17.0-testing-r1716-bin-linux.run
    mv $PKG_NAME-17.0-testing-r1716-bin-linux.run $PKG_NAME-$PKG_VERSION/$PKG_NAME-bin-linux.run
    mv $PKG_NAME-$PKG_VERSION build.$PKG_NAME-$PKG_VERSION
  fi

echo "copying sources..."
  rm -rf $PKG_NAME-$PKG_VERSION
  cp -R build.$PKG_NAME-$PKG_VERSION $PKG_NAME-$PKG_VERSION

for i in patches/$PKG_NAME-*.patch; do
  if [ -f "$i" ]; then
    echo "copying source patch..."
    echo $i
    cp $i $PKG_NAME-$PKG_VERSION
    if [ "$?" = "1" ]; then
      echo "error copying source patch: $1";exit 1
    fi
  fi
done

echo "moving sources..."
  mv $PKG_NAME-$PKG_VERSION ../build/script.module.audo-programs/resources/$PKG_NAME
  if [ "$?" = "1" ]; then
    echo "error building $PKG_NAME: $1";exit 1
  fi

echo "done"
exit 0
