#!/bin/sh

. packages/SABnzbd/meta
cd mkpkg

echo "building $PKG_NAME..."
echo "getting sources..."
  if [ ! -d build.$PKG_NAME-$PKG_VERSION-src ]; then
    wget $PKG_URL
    echo "extracting sources..."
    tar xzf $PKG_NAME-$PKG_VERSION-src.tar.gz
    mv $PKG_NAME-$PKG_VERSION build.$PKG_NAME-$PKG_VERSION-src
    rm $PKG_NAME-$PKG_VERSION-src.tar.gz
  fi

  echo "copying sources..."
   rm -rf $PKG_NAME-$PKG_VERSION
   cp -R build.$PKG_NAME-$PKG_VERSION-src $PKG_NAME-$PKG_VERSION

for i in patches/$PKG_NAME-*.patch; do
  if [ -f "$i" ]; then
    echo "patching sources..."
    echo $i
    cat $i | patch -p1 -d `echo "$PKG_NAME-$GIT_REV" | cut -f1 -d\ `
  fi
done

  echo "cleaning sources..."
    rm -rf $PKG_NAME-$PKG_VERSION/*.txt $PKG_NAME-$PKG_VERSION/Sample-* $PKG_NAME-$PKG_VERSION/PKG-INFO $PKG_NAME-$PKG_VERSION/licenses

  echo "moving sources..."
   mv $PKG_NAME-$PKG_VERSION ../build/script.module.audo-programs/resources/$PKG_NAME

  echo "done"
